### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/web-api-skeleton.log
      archivedLogFilenamePattern: logs/web-api-skeleton-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

locations:
  uhdsUrl: http://example.com/path-to-json-file.json
  icalUrl: https://www.google.com/calendar/ical/calendar-id%40group.calendar.google.com/public/basic.ics
  diningJsonOut: change-me.json
  icalOut: dining-changeme.ical
  cacheDirectory: cache
  campusmapUrl: http://campusmap.example.com?id=
  campusmapImageUrl: http://campusmap.example.com/images/
  extensionUrl: http://example.com/extension_locations.xml
  extensionXmlOut: extension-locations.xml
  apiEndpointUrl: https://api.example.com/v1/

database:
  driverClass: com.mysql.jdbc.Driver
  user: secret
  password: sauce
  url: jdbc:mysql://example.com:1234/dbname?useUnicode=true&amp;characterEncoding=UTF-8
  initialSize: 2
  minSize: 1
  maxSize: 4