swagger: '2.0'
info:
  title: Web API Skeleton
  description: Skeleton for Dropwizard Web APIs
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - http
basePath: /api/v0
paths:
  /:
    get:
      summary: Sample Resource
      description: This is a sample resource that returns a short message.
      responses:
        200:
          description: A short message
          schema:
            type: string
